### ISSUE TITLE
Disable unused source code

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/NCEPLIBS-sp#109]
NCEPLIBS-sp is used by CFS, UFS utils, NCEPLIBS-ip, and various other ops models. The following NCEPLIBS-sp subroutines (all of which correspond with <subroutine>.f source file) are not used in any of these packages: spfft spgradq spgradx spgrady sptgpmd sptgpsd sptgptd sptgptsd sptgptvd sptrund sptrunl spvar

Add a build option for these that's off by default.

**Comment by edwardhartnett** [comment]
A good way to do this is to make a build option to build without these. So if we discover some important user we missed, it's easy to turn them back on.

If we go a few releases without anyone complaining, then we can eliminate them from the repo.

**Comment by AlexanderRichert-NOAA** [comment]
Nice, that sounds good.
