### ISSUE TITLE
Add Spack CI

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/NCEPLIBS-sp#116]
I'd like to do the following for sp, and if it goes well, extend it to other NCEPLIBS:
1. Add a Spack-based CI workflow, following the example of grib_util (spack.yml)
2. Maintain an authoritative Spack recipe (package.py) somewhere within the NCEPLIBS-sp repository. ~~When doing a release, we'd have to "cheat" and make that version, say, a git commit rather than a (non yet existent) sha256 sum.~~
3. In the Spack CI, build sp using that recipe, including running ctest suite.
4. Consider adding a CI test to check whether the Spack recipe has a variant for each CMake build option.

Having the recipe in the repository means we can develop the code and the Spack recipe in tandem (immediately test new build options, etc.), and identify bugs quickly.

**Comment by AlexanderRichert-NOAA** [comment]
@edwardhartnett I've been kicking this around in my head for a bit, let me know what you think.

**Comment by edwardhartnett** [comment]
1 - Yes, please!
2 - I don't quite understand how this would work, can you demonstrate?
3 - Yes please!
4 - Certainly sounds like an interesting idea, can you demonstrate?

Also, after you have resolved all the issues to your satisfaction, we need to document this approach in the AGU paper.
