### ISSUE TITLE
what's the deal with master vs. develop branches?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-sp#38]
Most projects use master branch as the default branch, and that works fine.

I've worked on projects where many programmers were submitting pull requests every day, and we only ran testing once per day on a HPC system. In this case we had a develop branch, and we merged daily changes to it, and tested it on the HPC each night, so we could test all the day's changes together before merging to master.

In this case we also had an extra process step, which was that develop had to be merged to master each day after testing.

But on a project where we have CI and are testing every PR, there does not seem to be a need for a develop branch. And sure enough, the master branch is out of date. So we are just creating confusion by having both a master and develop.

I propose we get rid of develop and use master as the default branch. Developers of course will work on branches and we can protect master on GitHub so that it can only be modified via Pull Request.

@kgerheiser @Hang-Lei-NOAA what do you guys think? Anyone else have any comment?

**Comment by kgerheiser** [comment]
I am in favor. I like having `master` as the main branch.

**Comment by edwardhartnett** [comment]
We'll leave this for now...
