### ISSUE TITLE
Empty include_* directories installed

### ISSUE THREAD

**Issue by opoplawski** [NOAA-EMC/NCEPLIBS-sp#48]
Perhaps I should just wait until NOAA-EMC/NCEPLIBS-ip#226 is resolved, but I'm looking at packaging this for Fedora.  At the moment it install the following empty directories:
```
/usr/include_4
/usr/include_8
/usr/include_d
```
These directories are not allowed in Fedora.  If I remove them then the cmake modules cannot be imported because their interface directories have be removed.  One solution might be to have the option to install into /usr/include/splib/include_*.  Thoughts?

**Comment by edwardhartnett** [comment]
We hope to move on NOAA-EMC/NCEPLIBS-ip#226 soon, which will resolve this.

Of course, these directory names must go, and we will install in an "include" directory like everyone else in the world does.

**Comment by edwardhartnett** [comment]
Howdy @opoplawski ! 

I am about to do a release of sp and am looking at issues. I see that there are no include files in sp. So how about I just remove these directories from the CMake build as you suggest?

**Comment by opoplawski** [comment]
That would be great, thanks!
