### ISSUE TITLE
update doxygen in splat.F

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-sp#74]
Bring the documentation in splat.F up to current doxygen standards.

**Comment by AlexanderRichert-NOAA** [comment]
Do we care about column width of documentation, presuming it doesn't exceed 80 characters?

**Comment by edwardhartnett** [comment]
It can exceed 80 characters if it needs to (sometimes in tables, where you can't continue a line.)

Otherwise I use emacs M-x indent-region, which gives a nice 80-char line on the whole paragraph, without me having to figure out the line breaks. Your editor might have something similar.

Similarly emacs provides the M-x lower-case command to convert a region to lower-case. Hopefully your editor has something similar.
