### ISSUE TITLE
Remove the _8 version of this library from the build

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-sp#79]
In this library we are building the _4, _d, and _8 variants.

Does anyone actually use the _8? On other NCEPLIBS we have removed it. For example, the g2 library only builds _d and _4.

Can anyone shed any light on whether the _8 version of sp (and ip) are ever used? I would love to drop it!

@GeorgeGayno-NOAA @GeorgeVandenberghe-NOAA @AlexanderRichert-NOAA @climbfuji @kgerheiser @Hang-Lei-NOAA

**Comment by Hang-Lei-NOAA** [comment]
_4 and _d should be enough.
If we are removing _8, we need to coordinate the changes with other
libraries that used sp_8 in build.

**Comment by GeorgeGayno-NOAA** [comment]
UFS_UTILS does not use the "_8" version.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA do you know of anyone that uses the _8?

What does the ufs-weather-model use?

**Comment by AlexanderRichert-NOAA** [comment]
> @Hang-Lei-NOAA do you know of anyone that uses the _8?
> 
> What does the ufs-weather-model use?

Based on running various regression tests on Hera and also looking at cmake config files, UFS WM does not appear to use the _8 version of sp.

**Comment by edwardhartnett** [comment]
OK, I will remove _8 from the build system before the release, and if anyone complains, I may have to add it back and do another release. ;-)

**Comment by Hang-Lei-NOAA** [comment]
In NCEPLIBS,

bacio
bufr
ip
w3emc
w3nco

Still have _8 build

**Comment by edwardhartnett** [comment]
Yes, we will remove all of them.

Also bacio only has one build now, which is based on the _4. There is no _8 or _d for bacio any longer.

I will remove _8 from sp, ip, w3emc, and w3nco.
