### ISSUE TITLE
Add testing for _4 version of the library (currently only _d version is tested)

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-sp#81]
Add testing for _4 version of the library (currently only _d version is tested)

**Comment by AlexanderRichert-NOAA** [comment]
@edwardhartnett Was this fixed by https://github.com/NOAA-EMC/NCEPLIBS-sp/pull/95 (+ the PR for the splat test)?

**Comment by edwardhartnett** [comment]
Well not really, although that helped. But the other tests can be converted, if I could figure out how, so I left this issue open.

**Comment by AlexanderRichert-NOAA** [comment]
Resolved through ip merge.
